version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: sellhub-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sellhub
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: